name: dart_opensong
description: Support for OpenSong file formats in Dart.
repository: https://github.com/reformatus/dart_opensong
issue_tracker: https://github.com/reformatus/dart_opensong/issues
homepage: https://reflabs.hu/dart_opensong
documentation: https://reflabs.hu/dart_opensong/doc/api

version: 0.0.2

environment:
  sdk: ^3.7.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
