name: dart_opensong
description: Support for OpenSong file formats in Dart.
repository: https://github.com/reformatus/dart_opensong
issue_tracker: https://github.com/reformatus/dart_opensong/issues

version: 0.0.1-dev

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  petitparser: ^6.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
